/flychams/**:
  ros__parameters:
    # Global frames
    global_frames:
      world: "world"
    # Agent frames
    agent_frames:
      agent_local: "AGENTID/local"
      agent_body: "AGENTID/body"
      camera_body: "AGENTID/HEADID/body"
      camera_optical: "AGENTID/HEADID/optical"