/flychams/**:
  ros__parameters:
    # Nodes to launch
    dashboard: true
    metrics_factory: true
    marker_factory: true
    agent_assignment: true
    target_assignment: true
    cluster_assignment: true
    simulation: true
    control: true
    perception: true
