/flychams/**:
  ros__parameters:
    # Tracking parameters
    tracking:
      num_tracking_windows: 4 # For MultiWindowTracking mode
      min_apparent_size: 0.2  # Minimum fraction of half-sensor that the target will occupy in the image
      max_apparent_size: 0.9  # Maximum fraction of half-sensor that the target will occupy in the image
      ref_apparent_size: 0.8  # Reference fraction of half-sensor that the target will occupy in the image
    # Window IDs (for GUI purposes)
    fixed_window_ids: [
      scene_view: "SCENE"
      agent_view_0: "AGENT00"
      agent_view_1: "AGENT01"
      map_view: "MAP"
    ]
    dynamic_window_ids: [
      central_view: "CENTRAL"
      tracking_view_0: "TRACKING00"
      tracking_view_1: "TRACKING01"
      tracking_view_2: "TRACKING02"
      tracking_view_3: "TRACKING03"
    ]
    # Fixed camera IDs (for GUI purposes)
    fixed_camera_ids: [
      scene_camera: "CAM_SCENE"
      agent_camera_0: "CAM_AGENTID_00"
      agent_camera_1: "CAM_AGENTID_01"
      map_camera: ""
    ]
