/flychams/**:
  ros__parameters:
    config_source_file: "/home/testuser/FlyingChameleons/config/Configuration.xlsx"
    airsim_settings_destination_file: "/home/testuser/FlyingChameleons/config/settings.json"
    trajectory_root: "/home/testuser/FlyingChameleons/config/"