/flychams/**:
  ros__parameters:
    global_topics:
      registration: "global/registration"
      metrics: "global/metrics"
    agent_topics:
      global_odom: "/airsim/AGENTID/global/state/odom"
      position_goal: "agents/AGENTID/position/goal"
      tracking_info: "agents/AGENTID/tracking/info"
      tracking_goal: "agents/AGENTID/tracking/goal"
      metrics: "agents/AGENTID/visual/metrics"
      markers: "agents/AGENTID/visual/markers"
    target_topics:
      info: "targets/TARGETID/info"
      metrics: "targets/TARGETID/visual/metrics"
      markers: "targets/TARGETID/visual/markers"
    cluster_topics:
      info: "clusters/CLUSTERID/info"
      metrics: "clusters/CLUSTERID/visual/metrics"
      markers: "clusters/CLUSTERID/visual/markers"