/flychams/**:
  ros__parameters:
    # UAV control parameters
    uav_control:
      control_update_rate: 10.0 # (Hz)
      takeoff_altitude: 1.0     # (m)
      takeoff_timeout: 10.0     # (s)
      landing_timeout: 10.0     # (s)
      min_speed: 5.0            # (m/s)
      max_speed: 12.0           # (m/s)
      min_distance: 0.25        # (m)
      max_distance: 50.0        # (m)
      max_acceleration: 1.0     # (m/s^2)
    # Head control parameters
    head_control:
      control_update_rate: 20.0 # (Hz)